### ISSUE TITLE
Maintain session logs using IP Tables

### ISSUE THREAD

**Issue by sudheesh001** [NIT-Warangal/SCorner#10]
`DateTime logged in` || `IP address` || `DateTime logged out`

**Comment by sudheesh001** [comment]
schema changed in a72bedaf9a614749ef3d2e65fa5d2e11b7f01d7d and f1f048c63145406d5c00b0b20e5158ddc7cf07ac

**Comment by sudheesh001** [comment]
Why are the session statuses 1 and 2, keep it 1 and 0, that should be better

**Comment by kranthikiran01** [comment]
You gave it in database.sql file :sob:
