### ISSUE TITLE
Enabling/Disabling like and dislike buttons depending on the user's activity

### ISSUE THREAD

**Issue by kranthikiran01** [NIT-Warangal/SCorner#6]
Once the user likes/dislikes a post.....we need to disable/enable the like & dislike buttons accordingly. We need a schema change so that we can track what the user liked/disliked and not yet liked (Dont actually want to track every activity ). Any solution is welcome :blush: :+1:

**Comment by sudheesh001** [comment]
I think once a user gives his/her opinion either like or dislike, we should just transform those buttons to a tick symbol. This can probably be done by making a table of which user has liked which post `Sno`.

**Comment by kranthikiran01** [comment]
That will do i hope :+1:
